services:
  web:
    build: .
    container_name: portfolio
    # Mantenemos el comando, pero ahora corre como django_user
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn mi_proyecto.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    env_file:
      - .env
    expose:
      - "8000"
    # Seguridad extra: le decimos al compose que fuerce el usuario si fuera necesario
    user: "1000:1000"

  nginx:
    image: nginx:alpine
    container_name: nginx_portfolio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles:ro # 'ro' significa Read-Only (Solo lectura), muy bien ahí.
      - /etc/letsencrypt:/etc/letsencrypt:ro # También lo ponemos como solo lectura para Nginx
    depends_on:
      - web

volumes:
  static_volume:
